model:
  base_learning_rate: 4.5e-6
  target: ldm.models.autoencoder.VQModel
  params:
    monitor: "val/rec_loss"
    embed_dim: 3
    n_embed: 8192
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_conditional: false
        disc_in_channels: 3
        disc_num_layers: 2
        disc_start: 1
        disc_weight: 0.6

    ddconfig:
      double_z: false
      z_channels: 3
      resolution: 32
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [ 1,2 ]  # num_down = len(ch_mult)-1
      num_res_blocks: 1
      attn_resolutions: [ ]
      dropout: 0.0

data:
  target: config_utils.DataModuleFromConfig
  params:
    batch_size: 128
    wrap: True
    train:
      target: ldm.data.CIFAR.CIFAR10Train
    validation:
      target: ldm.data.CIFAR.CIFAR10Validation

lightning:
  callbacks:
    image_logger:
      target: config_utils.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 8
        increase_log_steps: True

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
