name: lvd
channels:
  - pytorch
  - defaults
dependencies:
  - python==3.9.10
  - pip==22.2.2
  - numpy==1.23.3
  - pytorch==1.12.0
  - torchvision==0.13.0
  - cudatoolkit==11.3.1
  - conda-forge::ffmpeg
  - pip:
      - pytorch_lightning==1.7.7
      - tqdm==4.64.1
      - h5py==3.7.0
      - imageio==2.22.2
      - matplotlib==3.6.1
      - scikit-video
      - av==10.0.0
      - gradio==3.7
      - moviepy==1.0.3
      - gdown
      - einops
      - omegaconf