name: lvd
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10.4
  - pip=22.2.2
  - conda-forge::ffmpeg
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - pip:
      - pytorch_lightning
      - tqdm
      - h5py
      - imageio