name: video
channels:
  - defaults
dependencies:
  - python==3.10.6
  - pip==22.2.2
  - numpy==1.23.3
  - tqdm==4.64.1
  - conda-forge::ffmpeg==4.3.1
  - pip:
    - pytube==12.1.0
    - beautifulsoup4==4.11.1
    - selenium==4.6.0
    - opencv-python==4.6.0.66
    - glob2==0.7
    - scenedetect[opencv]