trainer:
  params:
    devices: [0,1,2]
    benchmark: True
    max_steps: 200000

model:
  base_learning_rate: 1.0e-06
  target: lvd.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: video
    cond_stage_key: label
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    enable_first_stage: True
    unet_config:
      target: lvd.modules.diffusionmodules.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions:
          - 4
          - 2
          - 1
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 4
        dims: 2
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 256

    first_stage_config:
      target: lvd.models.vqvae.VQVAE
      params:
        ckpt_path: pretrained/epoch=68-step=16629.ckpt

    cond_stage_config:
      target: lvd.modules.encoders.ClassEmbedder
      params:
        embed_dim: 256
        key: label

data:
  target: datasets.video_dataset.VideoData
  params:
    data_path: data/ucf101
    batch_size: 16
    num_workers: 8
    resolution: 128
    sequence_length: 16


