trainer:
  params:
    gpus: 0,
    benchmark: True
    max_steps: 200000

model:
  target: lvd.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    cond_stage_key: class_label
    image_size: 64
    channels: 3
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions:
          - 4
          - 2
          - 1
        num_res_blocks: 2
        channel_mult:
          - 1
          - 2
          - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512

    first_stage_config:
      target: lvd.models.vqvae.VQVAE
      params:
        ckpt_path: pretrained\epoch=68-step=16629.ckpt

    cond_stage_config:
      target: ldm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 512
        key: class_label

data:
  target: datasets.video_dataset.VideoData
  params:
    data_path: data\ucf101
    batch_size: 2
    num_workers: 0
    resolution: 128
    sequence_length: 16


