running:
  params:
    gpus: 2
    gradient_clip_val: 1

model:
  target: lvd.models.diffusion.ddpm.LatentDiffusion
  params:


data:
  target:
  params:
    data_path: data\ucf101
    batch_size: 16
    num_workers: 8
    resolution: 128
    sequence_length: 16
