running:
  params:
    gradient_clip_val: 1

model:
  target: lvd.models.vqvae.VQVAE
  params:
    embedding_dim:
    n_codes: 2048
    n_hiddens: 240
    n_res_layers: 4
    downsample: (4,4,4)

data:
  target: datasets.video_dataset.VideoData
  params:
    data_path: data\ucf101
    batch_size: 16
    num_workers: 0
    resolution: 128
    sequence_length: 16

lightning:
  trainer:
    benchmark: True
    accumulate_grad_batches: 2
    gpus: 1